[0.0.5] added bunch more functions (untested)

diff --git a/scripts/deploy b/scripts/deploy
--- a/scripts/deploy
+++ b/scripts/deploy
@@ -13,14 +13,15 @@
 read -p "Username: " USERNAME
 read -p "Version:  " VERSION 
 
-# verify version number in module
-# if egrep -q "$VERSION" wasatch/__init__.py
-# then
-#     echo "Correct version in __init__.py"
-# else
-#     echo "Can't find $VERSION in __init__.py"
-#     exit 1
-# fi
+# verify version number in library
+DRIVER_H=WasatchVCPPLib/WasatchVCPPLib/Driver.h
+if egrep -q "libraryVersion = \"$VERSION\"" $DRIVER_H
+then
+    echo "Correct version in $DRIVER_H"
+else
+    echo "Can't find $VERSION in $DRIVER_H"
+    exit 1
+fi
 
 # verify version number is tagged
 if git tag | egrep -q $VERSION
